apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv
spec:
  capacity:
    storage: 1 Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    mountPath: 
      path: /mnt/data/postgres
      type: DirectoryOrCreate