apiVersion: v1
kind: PersistenVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ngulik-postgres
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce itu hanya boleh diakses dalam 1 pod (umumnya dinode yang sama)
  resources:
    requests:
      storage: 1Gi