apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgre-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Optional
  storageClassName: manual
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate